// Mocks generated by Mockito 5.4.4 from annotations
// in siren_marketplace/test/unit/domain/services/negotiation_service_counter_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i2;

import 'package:dart_either/dart_either.dart' as _i16;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:siren_marketplace/core/domain/entities/catch.dart' as _i13;
import 'package:siren_marketplace/core/domain/entities/offer.dart' as _i5;
import 'package:siren_marketplace/core/domain/entities/order.dart' as _i3;
import 'package:siren_marketplace/core/domain/entities/product.dart' as _i18;
import 'package:siren_marketplace/core/domain/enums/catch_status.dart' as _i14;
import 'package:siren_marketplace/core/domain/enums/offer_status.dart' as _i8;
import 'package:siren_marketplace/core/domain/enums/order_status.dart' as _i11;
import 'package:siren_marketplace/core/domain/enums/user_role.dart' as _i7;
import 'package:siren_marketplace/core/domain/repositories/i_catch_repository.dart'
    as _i12;
import 'package:siren_marketplace/core/domain/repositories/i_offer_repository.dart'
    as _i4;
import 'package:siren_marketplace/core/domain/repositories/i_order_repository.dart'
    as _i10;
import 'package:siren_marketplace/core/domain/repositories/i_product_repository.dart'
    as _i15;
import 'package:siren_marketplace/core/domain/value_objects/offer_terms.dart'
    as _i9;
import 'package:siren_marketplace/core/network/api_result.dart' as _i17;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeFuture_0<T1> extends _i1.SmartFake implements _i2.Future<T1> {
  _FakeFuture_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeOrder_1 extends _i1.SmartFake implements _i3.Order {
  _FakeOrder_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [IOfferRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIOfferRepository extends _i1.Mock implements _i4.IOfferRepository {
  MockIOfferRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Future<String> create(_i5.Offer? offer) => (super.noSuchMethod(
        Invocation.method(
          #create,
          [offer],
        ),
        returnValue: _i2.Future<String>.value(_i6.dummyValue<String>(
          this,
          Invocation.method(
            #create,
            [offer],
          ),
        )),
      ) as _i2.Future<String>);

  @override
  _i2.Future<List<_i5.Offer>> getAllOffers() => (super.noSuchMethod(
        Invocation.method(
          #getAllOffers,
          [],
        ),
        returnValue: _i2.Future<List<_i5.Offer>>.value(<_i5.Offer>[]),
      ) as _i2.Future<List<_i5.Offer>>);

  @override
  _i2.Future<_i5.Offer?> getById(String? offerId) => (super.noSuchMethod(
        Invocation.method(
          #getById,
          [offerId],
        ),
        returnValue: _i2.Future<_i5.Offer?>.value(),
      ) as _i2.Future<_i5.Offer?>);

  @override
  _i2.Future<List<_i5.Offer>> getByProductId(
    String? productId, {
    _i7.UserRole? role,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getByProductId,
          [productId],
          {#role: role},
        ),
        returnValue: _i2.Future<List<_i5.Offer>>.value(<_i5.Offer>[]),
      ) as _i2.Future<List<_i5.Offer>>);

  @override
  _i2.Future<List<_i5.Offer>> getByBuyerId(String? buyerId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getByBuyerId,
          [buyerId],
        ),
        returnValue: _i2.Future<List<_i5.Offer>>.value(<_i5.Offer>[]),
      ) as _i2.Future<List<_i5.Offer>>);

  @override
  _i2.Future<List<_i5.Offer>> getByFisherId(String? fisherId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getByFisherId,
          [fisherId],
        ),
        returnValue: _i2.Future<List<_i5.Offer>>.value(<_i5.Offer>[]),
      ) as _i2.Future<List<_i5.Offer>>);

  @override
  _i2.Future<List<_i5.Offer>> getByCatchIds(List<String>? catchIds) =>
      (super.noSuchMethod(
        Invocation.method(
          #getByCatchIds,
          [catchIds],
        ),
        returnValue: _i2.Future<List<_i5.Offer>>.value(<_i5.Offer>[]),
      ) as _i2.Future<List<_i5.Offer>>);

  @override
  _i2.Future<List<_i5.Offer>> getByStatus(_i8.OfferStatus? status) =>
      (super.noSuchMethod(
        Invocation.method(
          #getByStatus,
          [status],
        ),
        returnValue: _i2.Future<List<_i5.Offer>>.value(<_i5.Offer>[]),
      ) as _i2.Future<List<_i5.Offer>>);

  @override
  _i2.Future<List<_i5.Offer>> getPendingForUser(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPendingForUser,
          [userId],
        ),
        returnValue: _i2.Future<List<_i5.Offer>>.value(<_i5.Offer>[]),
      ) as _i2.Future<List<_i5.Offer>>);

  @override
  _i2.Future<void> update(_i5.Offer? offer) => (super.noSuchMethod(
        Invocation.method(
          #update,
          [offer],
        ),
        returnValue: _i2.Future<void>.value(),
        returnValueForMissingStub: _i2.Future<void>.value(),
      ) as _i2.Future<void>);

  @override
  _i2.Future<void> delete(String? offerId) => (super.noSuchMethod(
        Invocation.method(
          #delete,
          [offerId],
        ),
        returnValue: _i2.Future<void>.value(),
        returnValueForMissingStub: _i2.Future<void>.value(),
      ) as _i2.Future<void>);

  @override
  _i2.Future<_i3.Order?> acceptOffer(
    String? offerId,
    _i7.UserRole? role, {
    String? message,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #acceptOffer,
          [
            offerId,
            role,
          ],
          {#message: message},
        ),
        returnValue: _i2.Future<_i3.Order?>.value(),
      ) as _i2.Future<_i3.Order?>);

  @override
  _i2.Future<void> rejectOffer(
    String? offerId,
    _i7.UserRole? role, {
    String? message,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #rejectOffer,
          [
            offerId,
            role,
          ],
          {#message: message},
        ),
        returnValue: _i2.Future<void>.value(),
        returnValueForMissingStub: _i2.Future<void>.value(),
      ) as _i2.Future<void>);

  @override
  _i2.Future<void> counterOffer(
    String? offerId,
    _i7.UserRole? role,
    _i9.OfferTerms? terms,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #counterOffer,
          [
            offerId,
            role,
            terms,
          ],
        ),
        returnValue: _i2.Future<void>.value(),
        returnValueForMissingStub: _i2.Future<void>.value(),
      ) as _i2.Future<void>);

  @override
  _i2.Future<void> markAsViewed(
    String? offerId,
    _i7.UserRole? role,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #markAsViewed,
          [
            offerId,
            role,
          ],
        ),
        returnValue: _i2.Future<void>.value(),
        returnValueForMissingStub: _i2.Future<void>.value(),
      ) as _i2.Future<void>);

  @override
  _i2.Future<T> transaction<T>(_i2.Future<T> Function()? action) =>
      (super.noSuchMethod(
        Invocation.method(
          #transaction,
          [action],
        ),
        returnValue: _i6.ifNotNull(
              _i6.dummyValueOrNull<T>(
                this,
                Invocation.method(
                  #transaction,
                  [action],
                ),
              ),
              (T v) => _i2.Future<T>.value(v),
            ) ??
            _FakeFuture_0<T>(
              this,
              Invocation.method(
                #transaction,
                [action],
              ),
            ),
      ) as _i2.Future<T>);

  @override
  void clearCache() => super.noSuchMethod(
        Invocation.method(
          #clearCache,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [IOrderRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIOrderRepository extends _i1.Mock implements _i10.IOrderRepository {
  MockIOrderRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Future<String> create(_i3.Order? order) => (super.noSuchMethod(
        Invocation.method(
          #create,
          [order],
        ),
        returnValue: _i2.Future<String>.value(_i6.dummyValue<String>(
          this,
          Invocation.method(
            #create,
            [order],
          ),
        )),
      ) as _i2.Future<String>);

  @override
  _i2.Future<List<_i3.Order>> getAllOrders() => (super.noSuchMethod(
        Invocation.method(
          #getAllOrders,
          [],
        ),
        returnValue: _i2.Future<List<_i3.Order>>.value(<_i3.Order>[]),
      ) as _i2.Future<List<_i3.Order>>);

  @override
  _i2.Future<_i3.Order> getById(String? orderId) => (super.noSuchMethod(
        Invocation.method(
          #getById,
          [orderId],
        ),
        returnValue: _i2.Future<_i3.Order>.value(_FakeOrder_1(
          this,
          Invocation.method(
            #getById,
            [orderId],
          ),
        )),
      ) as _i2.Future<_i3.Order>);

  @override
  _i2.Future<_i3.Order?> getByOfferId(String? offerId) => (super.noSuchMethod(
        Invocation.method(
          #getByOfferId,
          [offerId],
        ),
        returnValue: _i2.Future<_i3.Order?>.value(),
      ) as _i2.Future<_i3.Order?>);

  @override
  _i2.Future<List<_i3.Order>> getByUserId(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getByUserId,
          [userId],
        ),
        returnValue: _i2.Future<List<_i3.Order>>.value(<_i3.Order>[]),
      ) as _i2.Future<List<_i3.Order>>);

  @override
  _i2.Future<List<_i3.Order>> getByFisherId(String? fisherId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getByFisherId,
          [fisherId],
        ),
        returnValue: _i2.Future<List<_i3.Order>>.value(<_i3.Order>[]),
      ) as _i2.Future<List<_i3.Order>>);

  @override
  _i2.Future<List<_i3.Order>> getByBuyerId(String? buyerId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getByBuyerId,
          [buyerId],
        ),
        returnValue: _i2.Future<List<_i3.Order>>.value(<_i3.Order>[]),
      ) as _i2.Future<List<_i3.Order>>);

  @override
  _i2.Future<List<_i3.Order>> getByStatus(_i11.OrderStatus? status) =>
      (super.noSuchMethod(
        Invocation.method(
          #getByStatus,
          [status],
        ),
        returnValue: _i2.Future<List<_i3.Order>>.value(<_i3.Order>[]),
      ) as _i2.Future<List<_i3.Order>>);

  @override
  _i2.Future<List<_i3.Order>> getReviewableOrders(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getReviewableOrders,
          [userId],
        ),
        returnValue: _i2.Future<List<_i3.Order>>.value(<_i3.Order>[]),
      ) as _i2.Future<List<_i3.Order>>);

  @override
  _i2.Future<void> update(_i3.Order? order) => (super.noSuchMethod(
        Invocation.method(
          #update,
          [order],
        ),
        returnValue: _i2.Future<void>.value(),
        returnValueForMissingStub: _i2.Future<void>.value(),
      ) as _i2.Future<void>);

  @override
  _i2.Future<void> delete(String? orderId) => (super.noSuchMethod(
        Invocation.method(
          #delete,
          [orderId],
        ),
        returnValue: _i2.Future<void>.value(),
        returnValueForMissingStub: _i2.Future<void>.value(),
      ) as _i2.Future<void>);

  @override
  _i2.Future<T> transaction<T>(_i2.Future<T> Function()? action) =>
      (super.noSuchMethod(
        Invocation.method(
          #transaction,
          [action],
        ),
        returnValue: _i6.ifNotNull(
              _i6.dummyValueOrNull<T>(
                this,
                Invocation.method(
                  #transaction,
                  [action],
                ),
              ),
              (T v) => _i2.Future<T>.value(v),
            ) ??
            _FakeFuture_0<T>(
              this,
              Invocation.method(
                #transaction,
                [action],
              ),
            ),
      ) as _i2.Future<T>);

  @override
  _i2.Future<_i3.Order> relistOrder(
    String? orderId,
    String? cancellationReason,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #relistOrder,
          [
            orderId,
            cancellationReason,
          ],
        ),
        returnValue: _i2.Future<_i3.Order>.value(_FakeOrder_1(
          this,
          Invocation.method(
            #relistOrder,
            [
              orderId,
              cancellationReason,
            ],
          ),
        )),
      ) as _i2.Future<_i3.Order>);
}

/// A class which mocks [ICatchRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockICatchRepository extends _i1.Mock implements _i12.ICatchRepository {
  MockICatchRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Future<String> create(_i13.Catch? catchItem) => (super.noSuchMethod(
        Invocation.method(
          #create,
          [catchItem],
        ),
        returnValue: _i2.Future<String>.value(_i6.dummyValue<String>(
          this,
          Invocation.method(
            #create,
            [catchItem],
          ),
        )),
      ) as _i2.Future<String>);

  @override
  _i2.Future<void> saveDraft(_i13.Catch? catchItem) => (super.noSuchMethod(
        Invocation.method(
          #saveDraft,
          [catchItem],
        ),
        returnValue: _i2.Future<void>.value(),
        returnValueForMissingStub: _i2.Future<void>.value(),
      ) as _i2.Future<void>);

  @override
  _i2.Future<_i13.Catch?> getById(String? catchId) => (super.noSuchMethod(
        Invocation.method(
          #getById,
          [catchId],
        ),
        returnValue: _i2.Future<_i13.Catch?>.value(),
      ) as _i2.Future<_i13.Catch?>);

  @override
  _i2.Future<List<_i13.Catch>> getByFisherId(String? fisherId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getByFisherId,
          [fisherId],
        ),
        returnValue: _i2.Future<List<_i13.Catch>>.value(<_i13.Catch>[]),
      ) as _i2.Future<List<_i13.Catch>>);

  @override
  _i2.Future<List<_i13.Catch>> getAvailableCatches() => (super.noSuchMethod(
        Invocation.method(
          #getAvailableCatches,
          [],
        ),
        returnValue: _i2.Future<List<_i13.Catch>>.value(<_i13.Catch>[]),
      ) as _i2.Future<List<_i13.Catch>>);

  @override
  _i2.Future<List<_i13.Catch>> getByStatus(_i14.CatchStatus? status) =>
      (super.noSuchMethod(
        Invocation.method(
          #getByStatus,
          [status],
        ),
        returnValue: _i2.Future<List<_i13.Catch>>.value(<_i13.Catch>[]),
      ) as _i2.Future<List<_i13.Catch>>);

  @override
  _i2.Future<List<_i13.Catch>> getExpiredCatches() => (super.noSuchMethod(
        Invocation.method(
          #getExpiredCatches,
          [],
        ),
        returnValue: _i2.Future<List<_i13.Catch>>.value(<_i13.Catch>[]),
      ) as _i2.Future<List<_i13.Catch>>);

  @override
  _i2.Future<List<_i13.Catch>> getCatchesForDeletion() => (super.noSuchMethod(
        Invocation.method(
          #getCatchesForDeletion,
          [],
        ),
        returnValue: _i2.Future<List<_i13.Catch>>.value(<_i13.Catch>[]),
      ) as _i2.Future<List<_i13.Catch>>);

  @override
  _i2.Future<void> update(_i13.Catch? catchItem) => (super.noSuchMethod(
        Invocation.method(
          #update,
          [catchItem],
        ),
        returnValue: _i2.Future<void>.value(),
        returnValueForMissingStub: _i2.Future<void>.value(),
      ) as _i2.Future<void>);

  @override
  _i2.Future<void> delete(String? catchId) => (super.noSuchMethod(
        Invocation.method(
          #delete,
          [catchId],
        ),
        returnValue: _i2.Future<void>.value(),
        returnValueForMissingStub: _i2.Future<void>.value(),
      ) as _i2.Future<void>);

  @override
  _i2.Future<void> updateBatch(List<_i13.Catch>? catches) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateBatch,
          [catches],
        ),
        returnValue: _i2.Future<void>.value(),
        returnValueForMissingStub: _i2.Future<void>.value(),
      ) as _i2.Future<void>);

  @override
  _i2.Future<void> deleteBatch(List<String>? catchIds) => (super.noSuchMethod(
        Invocation.method(
          #deleteBatch,
          [catchIds],
        ),
        returnValue: _i2.Future<void>.value(),
        returnValueForMissingStub: _i2.Future<void>.value(),
      ) as _i2.Future<void>);

  @override
  _i2.Future<String> publishDraft(_i13.Catch? draft) => (super.noSuchMethod(
        Invocation.method(
          #publishDraft,
          [draft],
        ),
        returnValue: _i2.Future<String>.value(_i6.dummyValue<String>(
          this,
          Invocation.method(
            #publishDraft,
            [draft],
          ),
        )),
      ) as _i2.Future<String>);

  @override
  _i2.Future<void> saveLocalBatch(List<_i13.Catch>? catches) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveLocalBatch,
          [catches],
        ),
        returnValue: _i2.Future<void>.value(),
        returnValueForMissingStub: _i2.Future<void>.value(),
      ) as _i2.Future<void>);
}

/// A class which mocks [IProductRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIProductRepository extends _i1.Mock
    implements _i15.IProductRepository {
  MockIProductRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Future<_i16.Either<_i17.Failure, List<_i18.Product>>> getFisherProducts({
    int? page = 1,
    String? userId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFisherProducts,
          [],
          {
            #page: page,
            #userId: userId,
          },
        ),
        returnValue:
            _i2.Future<_i16.Either<_i17.Failure, List<_i18.Product>>>.value(
                _i6.dummyValue<_i16.Either<_i17.Failure, List<_i18.Product>>>(
          this,
          Invocation.method(
            #getFisherProducts,
            [],
            {
              #page: page,
              #userId: userId,
            },
          ),
        )),
      ) as _i2.Future<_i16.Either<_i17.Failure, List<_i18.Product>>>);

  @override
  _i2.Future<_i16.Either<_i17.Failure, _i18.Product?>> getProductById(
          String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getProductById,
          [id],
        ),
        returnValue: _i2.Future<_i16.Either<_i17.Failure, _i18.Product?>>.value(
            _i6.dummyValue<_i16.Either<_i17.Failure, _i18.Product?>>(
          this,
          Invocation.method(
            #getProductById,
            [id],
          ),
        )),
      ) as _i2.Future<_i16.Either<_i17.Failure, _i18.Product?>>);

  @override
  _i2.Future<_i16.Either<_i17.Failure, List<_i5.Offer>>> getProductOffers(
          String? productId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getProductOffers,
          [productId],
        ),
        returnValue:
            _i2.Future<_i16.Either<_i17.Failure, List<_i5.Offer>>>.value(
                _i6.dummyValue<_i16.Either<_i17.Failure, List<_i5.Offer>>>(
          this,
          Invocation.method(
            #getProductOffers,
            [productId],
          ),
        )),
      ) as _i2.Future<_i16.Either<_i17.Failure, List<_i5.Offer>>>);

  @override
  _i2.Future<_i16.Either<_i17.Failure, bool>> deleteProduct(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteProduct,
          [id],
        ),
        returnValue: _i2.Future<_i16.Either<_i17.Failure, bool>>.value(
            _i6.dummyValue<_i16.Either<_i17.Failure, bool>>(
          this,
          Invocation.method(
            #deleteProduct,
            [id],
          ),
        )),
      ) as _i2.Future<_i16.Either<_i17.Failure, bool>>);

  @override
  _i2.Future<_i16.Either<_i17.Failure, _i18.Product>> updateProduct(
    String? id, {
    required double? pricePerKg,
    required double? finalPrice,
    required double? availableWeight,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateProduct,
          [id],
          {
            #pricePerKg: pricePerKg,
            #finalPrice: finalPrice,
            #availableWeight: availableWeight,
          },
        ),
        returnValue: _i2.Future<_i16.Either<_i17.Failure, _i18.Product>>.value(
            _i6.dummyValue<_i16.Either<_i17.Failure, _i18.Product>>(
          this,
          Invocation.method(
            #updateProduct,
            [id],
            {
              #pricePerKg: pricePerKg,
              #finalPrice: finalPrice,
              #availableWeight: availableWeight,
            },
          ),
        )),
      ) as _i2.Future<_i16.Either<_i17.Failure, _i18.Product>>);

  @override
  _i2.Future<_i16.Either<_i17.Failure, List<_i18.Product>>>
      getAvailableProducts() => (super.noSuchMethod(
            Invocation.method(
              #getAvailableProducts,
              [],
            ),
            returnValue: _i2
                .Future<_i16.Either<_i17.Failure, List<_i18.Product>>>.value(
                _i6.dummyValue<_i16.Either<_i17.Failure, List<_i18.Product>>>(
              this,
              Invocation.method(
                #getAvailableProducts,
                [],
              ),
            )),
          ) as _i2.Future<_i16.Either<_i17.Failure, List<_i18.Product>>>);
}
