// Mocks generated by Mockito 5.4.4 from annotations
// in siren_marketplace/test/unit/domain/services/session_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i10;
import 'package:siren_marketplace/core/data/api/models/auth_api_models.dart'
    as _i2;
import 'package:siren_marketplace/core/data/sources/api/auth_api_data_source.dart'
    as _i9;
import 'package:siren_marketplace/core/data/storage/token_storage.dart' as _i11;
import 'package:siren_marketplace/core/domain/entities/user.dart' as _i5;
import 'package:siren_marketplace/core/domain/enums/user_role.dart' as _i6;
import 'package:siren_marketplace/core/domain/repositories/i_session_repository.dart'
    as _i3;
import 'package:siren_marketplace/core/domain/repositories/i_user_repository.dart'
    as _i7;
import 'package:siren_marketplace/core/domain/value_objects/rating.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAuthorizeResponse_0 extends _i1.SmartFake
    implements _i2.AuthorizeResponse {
  _FakeAuthorizeResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAccountApiModel_1 extends _i1.SmartFake
    implements _i2.AccountApiModel {
  _FakeAccountApiModel_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ISessionRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockISessionRepository extends _i1.Mock
    implements _i3.ISessionRepository {
  @override
  _i4.Future<_i5.User?> getCurrentUser() => (super.noSuchMethod(
        Invocation.method(
          #getCurrentUser,
          [],
        ),
        returnValue: _i4.Future<_i5.User?>.value(),
        returnValueForMissingStub: _i4.Future<_i5.User?>.value(),
      ) as _i4.Future<_i5.User?>);

  @override
  _i4.Future<_i6.UserRole?> getCurrentRole() => (super.noSuchMethod(
        Invocation.method(
          #getCurrentRole,
          [],
        ),
        returnValue: _i4.Future<_i6.UserRole?>.value(),
        returnValueForMissingStub: _i4.Future<_i6.UserRole?>.value(),
      ) as _i4.Future<_i6.UserRole?>);

  @override
  _i4.Future<void> saveCurrentUser(_i5.User? user) => (super.noSuchMethod(
        Invocation.method(
          #saveCurrentUser,
          [user],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> saveCurrentRole(_i6.UserRole? role) => (super.noSuchMethod(
        Invocation.method(
          #saveCurrentRole,
          [role],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> clearSession() => (super.noSuchMethod(
        Invocation.method(
          #clearSession,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<bool> isLoggedIn() => (super.noSuchMethod(
        Invocation.method(
          #isLoggedIn,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
        returnValueForMissingStub: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);
}

/// A class which mocks [IUserRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIUserRepository extends _i1.Mock implements _i7.IUserRepository {
  @override
  _i4.Future<_i5.User?> getById(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #getById,
          [userId],
        ),
        returnValue: _i4.Future<_i5.User?>.value(),
        returnValueForMissingStub: _i4.Future<_i5.User?>.value(),
      ) as _i4.Future<_i5.User?>);

  @override
  _i4.Future<List<_i5.User>> getByIds(List<String>? userIds) =>
      (super.noSuchMethod(
        Invocation.method(
          #getByIds,
          [userIds],
        ),
        returnValue: _i4.Future<List<_i5.User>>.value(<_i5.User>[]),
        returnValueForMissingStub:
            _i4.Future<List<_i5.User>>.value(<_i5.User>[]),
      ) as _i4.Future<List<_i5.User>>);

  @override
  _i4.Future<void> updateRole(
    String? userId,
    _i6.UserRole? role,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateRole,
          [
            userId,
            role,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateRating({
    required String? userId,
    required _i8.Rating? rating,
    required int? reviewCount,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateRating,
          [],
          {
            #userId: userId,
            #rating: rating,
            #reviewCount: reviewCount,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> update(_i5.User? user) => (super.noSuchMethod(
        Invocation.method(
          #update,
          [user],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<bool> exists(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #exists,
          [userId],
        ),
        returnValue: _i4.Future<bool>.value(false),
        returnValueForMissingStub: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<void> create(_i5.User? user) => (super.noSuchMethod(
        Invocation.method(
          #create,
          [user],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i5.User?> getFirstFisher() => (super.noSuchMethod(
        Invocation.method(
          #getFirstFisher,
          [],
        ),
        returnValue: _i4.Future<_i5.User?>.value(),
        returnValueForMissingStub: _i4.Future<_i5.User?>.value(),
      ) as _i4.Future<_i5.User?>);

  @override
  _i4.Future<_i5.User?> getFirstBuyer() => (super.noSuchMethod(
        Invocation.method(
          #getFirstBuyer,
          [],
        ),
        returnValue: _i4.Future<_i5.User?>.value(),
        returnValueForMissingStub: _i4.Future<_i5.User?>.value(),
      ) as _i4.Future<_i5.User?>);

  @override
  _i4.Future<void> saveLocal(_i5.User? user) => (super.noSuchMethod(
        Invocation.method(
          #saveLocal,
          [user],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [IAuthApiDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockIAuthApiDataSource extends _i1.Mock
    implements _i9.IAuthApiDataSource {
  @override
  _i4.Future<_i2.AuthorizeResponse> login(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [
            email,
            password,
          ],
        ),
        returnValue:
            _i4.Future<_i2.AuthorizeResponse>.value(_FakeAuthorizeResponse_0(
          this,
          Invocation.method(
            #login,
            [
              email,
              password,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.AuthorizeResponse>.value(_FakeAuthorizeResponse_0(
          this,
          Invocation.method(
            #login,
            [
              email,
              password,
            ],
          ),
        )),
      ) as _i4.Future<_i2.AuthorizeResponse>);

  @override
  _i4.Future<_i2.AccountApiModel> getMyProfile() => (super.noSuchMethod(
        Invocation.method(
          #getMyProfile,
          [],
        ),
        returnValue:
            _i4.Future<_i2.AccountApiModel>.value(_FakeAccountApiModel_1(
          this,
          Invocation.method(
            #getMyProfile,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.AccountApiModel>.value(_FakeAccountApiModel_1(
          this,
          Invocation.method(
            #getMyProfile,
            [],
          ),
        )),
      ) as _i4.Future<_i2.AccountApiModel>);

  @override
  _i4.Future<void> logout() => (super.noSuchMethod(
        Invocation.method(
          #logout,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i2.AuthorizeResponse> authenticate() => (super.noSuchMethod(
        Invocation.method(
          #authenticate,
          [],
        ),
        returnValue:
            _i4.Future<_i2.AuthorizeResponse>.value(_FakeAuthorizeResponse_0(
          this,
          Invocation.method(
            #authenticate,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.AuthorizeResponse>.value(_FakeAuthorizeResponse_0(
          this,
          Invocation.method(
            #authenticate,
            [],
          ),
        )),
      ) as _i4.Future<_i2.AuthorizeResponse>);

  @override
  _i4.Future<String> refreshToken() => (super.noSuchMethod(
        Invocation.method(
          #refreshToken,
          [],
        ),
        returnValue: _i4.Future<String>.value(_i10.dummyValue<String>(
          this,
          Invocation.method(
            #refreshToken,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<String>.value(_i10.dummyValue<String>(
          this,
          Invocation.method(
            #refreshToken,
            [],
          ),
        )),
      ) as _i4.Future<String>);
}

/// A class which mocks [TokenStorage].
///
/// See the documentation for Mockito's code generation for more information.
class MockTokenStorage extends _i1.Mock implements _i11.TokenStorage {
  @override
  _i4.Future<void> saveAccessToken(String? token) => (super.noSuchMethod(
        Invocation.method(
          #saveAccessToken,
          [token],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<String?> getAccessToken() => (super.noSuchMethod(
        Invocation.method(
          #getAccessToken,
          [],
        ),
        returnValue: _i4.Future<String?>.value(),
        returnValueForMissingStub: _i4.Future<String?>.value(),
      ) as _i4.Future<String?>);

  @override
  _i4.Future<void> saveRefreshToken(String? token) => (super.noSuchMethod(
        Invocation.method(
          #saveRefreshToken,
          [token],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<String?> getRefreshToken() => (super.noSuchMethod(
        Invocation.method(
          #getRefreshToken,
          [],
        ),
        returnValue: _i4.Future<String?>.value(),
        returnValueForMissingStub: _i4.Future<String?>.value(),
      ) as _i4.Future<String?>);

  @override
  _i4.Future<void> saveTokenExpiry(DateTime? expiry) => (super.noSuchMethod(
        Invocation.method(
          #saveTokenExpiry,
          [expiry],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<DateTime?> getTokenExpiry() => (super.noSuchMethod(
        Invocation.method(
          #getTokenExpiry,
          [],
        ),
        returnValue: _i4.Future<DateTime?>.value(),
        returnValueForMissingStub: _i4.Future<DateTime?>.value(),
      ) as _i4.Future<DateTime?>);

  @override
  _i4.Future<bool> isTokenExpired() => (super.noSuchMethod(
        Invocation.method(
          #isTokenExpired,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
        returnValueForMissingStub: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<void> saveUserId(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #saveUserId,
          [userId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<String?> getUserId() => (super.noSuchMethod(
        Invocation.method(
          #getUserId,
          [],
        ),
        returnValue: _i4.Future<String?>.value(),
        returnValueForMissingStub: _i4.Future<String?>.value(),
      ) as _i4.Future<String?>);

  @override
  _i4.Future<void> saveToken(
    String? accessToken, {
    String? refreshToken,
    DateTime? expiry,
    String? userId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveToken,
          [accessToken],
          {
            #refreshToken: refreshToken,
            #expiry: expiry,
            #userId: userId,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> clearTokens() => (super.noSuchMethod(
        Invocation.method(
          #clearTokens,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<bool> isAuthenticated() => (super.noSuchMethod(
        Invocation.method(
          #isAuthenticated,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
        returnValueForMissingStub: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);
}
