// Mocks generated by Mockito 5.4.6 from annotations
// in siren_marketplace/test/helpers/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i2;

import 'package:dart_either/dart_either.dart' as _i24;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i11;
import 'package:siren_marketplace/core/data/api/models/offer_api_models.dart'
    as _i34;
import 'package:siren_marketplace/core/data/datasources/interfaces/i_catch_datasource.dart'
    as _i31;
import 'package:siren_marketplace/core/data/datasources/interfaces/i_offer_datasource.dart'
    as _i33;
import 'package:siren_marketplace/core/data/datasources/interfaces/i_order_datasource.dart'
    as _i35;
import 'package:siren_marketplace/core/data/datasources/interfaces/i_review_datasource.dart'
    as _i37;
import 'package:siren_marketplace/core/data/datasources/interfaces/i_session_datasource.dart'
    as _i39;
import 'package:siren_marketplace/core/data/datasources/interfaces/i_user_datasource.dart'
    as _i41;
import 'package:siren_marketplace/core/data/models/catch_model.dart' as _i32;
import 'package:siren_marketplace/core/data/models/offer_model.dart' as _i8;
import 'package:siren_marketplace/core/data/models/order_model.dart' as _i36;
import 'package:siren_marketplace/core/data/models/review_model.dart' as _i38;
import 'package:siren_marketplace/core/data/models/user_model.dart' as _i40;
import 'package:siren_marketplace/core/domain/entities/catch.dart' as _i10;
import 'package:siren_marketplace/core/domain/entities/message.dart' as _i4;
import 'package:siren_marketplace/core/domain/entities/offer.dart' as _i5;
import 'package:siren_marketplace/core/domain/entities/order.dart' as _i3;
import 'package:siren_marketplace/core/domain/entities/product.dart' as _i26;
import 'package:siren_marketplace/core/domain/entities/review.dart' as _i6;
import 'package:siren_marketplace/core/domain/entities/user.dart' as _i7;
import 'package:siren_marketplace/core/domain/enums/catch_status.dart' as _i12;
import 'package:siren_marketplace/core/domain/enums/offer_status.dart' as _i15;
import 'package:siren_marketplace/core/domain/enums/order_status.dart' as _i18;
import 'package:siren_marketplace/core/domain/enums/user_role.dart' as _i14;
import 'package:siren_marketplace/core/domain/repositories/i_catch_repository.dart'
    as _i9;
import 'package:siren_marketplace/core/domain/repositories/i_offer_repository.dart'
    as _i13;
import 'package:siren_marketplace/core/domain/repositories/i_order_repository.dart'
    as _i17;
import 'package:siren_marketplace/core/domain/repositories/i_product_repository.dart'
    as _i23;
import 'package:siren_marketplace/core/domain/repositories/i_review_repository.dart'
    as _i19;
import 'package:siren_marketplace/core/domain/repositories/i_session_repository.dart'
    as _i20;
import 'package:siren_marketplace/core/domain/repositories/i_user_repository.dart'
    as _i21;
import 'package:siren_marketplace/core/domain/services/message_service.dart'
    as _i27;
import 'package:siren_marketplace/core/domain/services/negotiation_service.dart'
    as _i28;
import 'package:siren_marketplace/core/domain/services/rating_service.dart'
    as _i29;
import 'package:siren_marketplace/core/domain/services/session_service.dart'
    as _i30;
import 'package:siren_marketplace/core/domain/value_objects/offer_terms.dart'
    as _i16;
import 'package:siren_marketplace/core/domain/value_objects/rating.dart'
    as _i22;
import 'package:siren_marketplace/core/network/api_result.dart' as _i25;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeFuture_0<T1> extends _i1.SmartFake implements _i2.Future<T1> {
  _FakeFuture_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeOrder_1 extends _i1.SmartFake implements _i3.Order {
  _FakeOrder_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMessage_2 extends _i1.SmartFake implements _i4.Message {
  _FakeMessage_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeOffer_3 extends _i1.SmartFake implements _i5.Offer {
  _FakeOffer_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeReview_4 extends _i1.SmartFake implements _i6.Review {
  _FakeReview_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUser_5 extends _i1.SmartFake implements _i7.User {
  _FakeUser_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeOfferModel_6 extends _i1.SmartFake implements _i8.OfferModel {
  _FakeOfferModel_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ICatchRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockICatchRepository extends _i1.Mock implements _i9.ICatchRepository {
  MockICatchRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Future<String> create(_i10.Catch? catchItem) =>
      (super.noSuchMethod(
            Invocation.method(#create, [catchItem]),
            returnValue: _i2.Future<String>.value(
              _i11.dummyValue<String>(
                this,
                Invocation.method(#create, [catchItem]),
              ),
            ),
          )
          as _i2.Future<String>);

  @override
  _i2.Future<void> saveDraft(_i10.Catch? catchItem) =>
      (super.noSuchMethod(
            Invocation.method(#saveDraft, [catchItem]),
            returnValue: _i2.Future<void>.value(),
            returnValueForMissingStub: _i2.Future<void>.value(),
          )
          as _i2.Future<void>);

  @override
  _i2.Future<_i10.Catch?> getById(String? catchId) =>
      (super.noSuchMethod(
            Invocation.method(#getById, [catchId]),
            returnValue: _i2.Future<_i10.Catch?>.value(),
          )
          as _i2.Future<_i10.Catch?>);

  @override
  _i2.Future<List<_i10.Catch>> getByFisherId(String? fisherId) =>
      (super.noSuchMethod(
            Invocation.method(#getByFisherId, [fisherId]),
            returnValue: _i2.Future<List<_i10.Catch>>.value(<_i10.Catch>[]),
          )
          as _i2.Future<List<_i10.Catch>>);

  @override
  _i2.Future<List<_i10.Catch>> getAvailableCatches() =>
      (super.noSuchMethod(
            Invocation.method(#getAvailableCatches, []),
            returnValue: _i2.Future<List<_i10.Catch>>.value(<_i10.Catch>[]),
          )
          as _i2.Future<List<_i10.Catch>>);

  @override
  _i2.Future<List<_i10.Catch>> getByStatus(_i12.CatchStatus? status) =>
      (super.noSuchMethod(
            Invocation.method(#getByStatus, [status]),
            returnValue: _i2.Future<List<_i10.Catch>>.value(<_i10.Catch>[]),
          )
          as _i2.Future<List<_i10.Catch>>);

  @override
  _i2.Future<List<_i10.Catch>> getExpiredCatches() =>
      (super.noSuchMethod(
            Invocation.method(#getExpiredCatches, []),
            returnValue: _i2.Future<List<_i10.Catch>>.value(<_i10.Catch>[]),
          )
          as _i2.Future<List<_i10.Catch>>);

  @override
  _i2.Future<List<_i10.Catch>> getCatchesForDeletion() =>
      (super.noSuchMethod(
            Invocation.method(#getCatchesForDeletion, []),
            returnValue: _i2.Future<List<_i10.Catch>>.value(<_i10.Catch>[]),
          )
          as _i2.Future<List<_i10.Catch>>);

  @override
  _i2.Future<void> update(_i10.Catch? catchItem) =>
      (super.noSuchMethod(
            Invocation.method(#update, [catchItem]),
            returnValue: _i2.Future<void>.value(),
            returnValueForMissingStub: _i2.Future<void>.value(),
          )
          as _i2.Future<void>);

  @override
  _i2.Future<void> delete(String? catchId) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [catchId]),
            returnValue: _i2.Future<void>.value(),
            returnValueForMissingStub: _i2.Future<void>.value(),
          )
          as _i2.Future<void>);

  @override
  _i2.Future<void> updateBatch(List<_i10.Catch>? catches) =>
      (super.noSuchMethod(
            Invocation.method(#updateBatch, [catches]),
            returnValue: _i2.Future<void>.value(),
            returnValueForMissingStub: _i2.Future<void>.value(),
          )
          as _i2.Future<void>);

  @override
  _i2.Future<void> deleteBatch(List<String>? catchIds) =>
      (super.noSuchMethod(
            Invocation.method(#deleteBatch, [catchIds]),
            returnValue: _i2.Future<void>.value(),
            returnValueForMissingStub: _i2.Future<void>.value(),
          )
          as _i2.Future<void>);

  @override
  _i2.Future<String> publishDraft(_i10.Catch? draft) =>
      (super.noSuchMethod(
            Invocation.method(#publishDraft, [draft]),
            returnValue: _i2.Future<String>.value(
              _i11.dummyValue<String>(
                this,
                Invocation.method(#publishDraft, [draft]),
              ),
            ),
          )
          as _i2.Future<String>);
}

/// A class which mocks [IOfferRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIOfferRepository extends _i1.Mock implements _i13.IOfferRepository {
  MockIOfferRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Future<String> create(_i5.Offer? offer) =>
      (super.noSuchMethod(
            Invocation.method(#create, [offer]),
            returnValue: _i2.Future<String>.value(
              _i11.dummyValue<String>(
                this,
                Invocation.method(#create, [offer]),
              ),
            ),
          )
          as _i2.Future<String>);

  @override
  _i2.Future<List<_i5.Offer>> getAllOffers() =>
      (super.noSuchMethod(
            Invocation.method(#getAllOffers, []),
            returnValue: _i2.Future<List<_i5.Offer>>.value(<_i5.Offer>[]),
          )
          as _i2.Future<List<_i5.Offer>>);

  @override
  _i2.Future<_i5.Offer?> getById(String? offerId) =>
      (super.noSuchMethod(
            Invocation.method(#getById, [offerId]),
            returnValue: _i2.Future<_i5.Offer?>.value(),
          )
          as _i2.Future<_i5.Offer?>);

  @override
  _i2.Future<List<_i5.Offer>> getByProductId(
    String? productId, {
    _i14.UserRole? role,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getByProductId, [productId], {#role: role}),
            returnValue: _i2.Future<List<_i5.Offer>>.value(<_i5.Offer>[]),
          )
          as _i2.Future<List<_i5.Offer>>);

  @override
  _i2.Future<List<_i5.Offer>> getByBuyerId(String? buyerId) =>
      (super.noSuchMethod(
            Invocation.method(#getByBuyerId, [buyerId]),
            returnValue: _i2.Future<List<_i5.Offer>>.value(<_i5.Offer>[]),
          )
          as _i2.Future<List<_i5.Offer>>);

  @override
  _i2.Future<List<_i5.Offer>> getByFisherId(String? fisherId) =>
      (super.noSuchMethod(
            Invocation.method(#getByFisherId, [fisherId]),
            returnValue: _i2.Future<List<_i5.Offer>>.value(<_i5.Offer>[]),
          )
          as _i2.Future<List<_i5.Offer>>);

  @override
  _i2.Future<List<_i5.Offer>> getByCatchIds(List<String>? catchIds) =>
      (super.noSuchMethod(
            Invocation.method(#getByCatchIds, [catchIds]),
            returnValue: _i2.Future<List<_i5.Offer>>.value(<_i5.Offer>[]),
          )
          as _i2.Future<List<_i5.Offer>>);

  @override
  _i2.Future<List<_i5.Offer>> getByStatus(_i15.OfferStatus? status) =>
      (super.noSuchMethod(
            Invocation.method(#getByStatus, [status]),
            returnValue: _i2.Future<List<_i5.Offer>>.value(<_i5.Offer>[]),
          )
          as _i2.Future<List<_i5.Offer>>);

  @override
  _i2.Future<List<_i5.Offer>> getPendingForUser(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getPendingForUser, [userId]),
            returnValue: _i2.Future<List<_i5.Offer>>.value(<_i5.Offer>[]),
          )
          as _i2.Future<List<_i5.Offer>>);

  @override
  _i2.Future<void> update(_i5.Offer? offer) =>
      (super.noSuchMethod(
            Invocation.method(#update, [offer]),
            returnValue: _i2.Future<void>.value(),
            returnValueForMissingStub: _i2.Future<void>.value(),
          )
          as _i2.Future<void>);

  @override
  _i2.Future<void> delete(String? offerId) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [offerId]),
            returnValue: _i2.Future<void>.value(),
            returnValueForMissingStub: _i2.Future<void>.value(),
          )
          as _i2.Future<void>);

  @override
  _i2.Future<_i3.Order?> acceptOffer(
    String? offerId,
    _i14.UserRole? role, {
    String? message,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #acceptOffer,
              [offerId, role],
              {#message: message},
            ),
            returnValue: _i2.Future<_i3.Order?>.value(),
          )
          as _i2.Future<_i3.Order?>);

  @override
  _i2.Future<void> rejectOffer(
    String? offerId,
    _i14.UserRole? role, {
    String? message,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #rejectOffer,
              [offerId, role],
              {#message: message},
            ),
            returnValue: _i2.Future<void>.value(),
            returnValueForMissingStub: _i2.Future<void>.value(),
          )
          as _i2.Future<void>);

  @override
  _i2.Future<void> counterOffer(
    String? offerId,
    _i14.UserRole? role,
    _i16.OfferTerms? terms,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#counterOffer, [offerId, role, terms]),
            returnValue: _i2.Future<void>.value(),
            returnValueForMissingStub: _i2.Future<void>.value(),
          )
          as _i2.Future<void>);

  @override
  _i2.Future<void> markAsViewed(String? offerId, _i14.UserRole? role) =>
      (super.noSuchMethod(
            Invocation.method(#markAsViewed, [offerId, role]),
            returnValue: _i2.Future<void>.value(),
            returnValueForMissingStub: _i2.Future<void>.value(),
          )
          as _i2.Future<void>);

  @override
  _i2.Future<T> transaction<T>(_i2.Future<T> Function()? action) =>
      (super.noSuchMethod(
            Invocation.method(#transaction, [action]),
            returnValue:
                _i11.ifNotNull(
                  _i11.dummyValueOrNull<T>(
                    this,
                    Invocation.method(#transaction, [action]),
                  ),
                  (T v) => _i2.Future<T>.value(v),
                ) ??
                _FakeFuture_0<T>(
                  this,
                  Invocation.method(#transaction, [action]),
                ),
          )
          as _i2.Future<T>);
}

/// A class which mocks [IOrderRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIOrderRepository extends _i1.Mock implements _i17.IOrderRepository {
  MockIOrderRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Future<String> create(_i3.Order? order) =>
      (super.noSuchMethod(
            Invocation.method(#create, [order]),
            returnValue: _i2.Future<String>.value(
              _i11.dummyValue<String>(
                this,
                Invocation.method(#create, [order]),
              ),
            ),
          )
          as _i2.Future<String>);

  @override
  _i2.Future<List<_i3.Order>> getAllOrders() =>
      (super.noSuchMethod(
            Invocation.method(#getAllOrders, []),
            returnValue: _i2.Future<List<_i3.Order>>.value(<_i3.Order>[]),
          )
          as _i2.Future<List<_i3.Order>>);

  @override
  _i2.Future<_i3.Order> getById(String? orderId) =>
      (super.noSuchMethod(
            Invocation.method(#getById, [orderId]),
            returnValue: _i2.Future<_i3.Order>.value(
              _FakeOrder_1(this, Invocation.method(#getById, [orderId])),
            ),
          )
          as _i2.Future<_i3.Order>);

  @override
  _i2.Future<_i3.Order?> getByOfferId(String? offerId) =>
      (super.noSuchMethod(
            Invocation.method(#getByOfferId, [offerId]),
            returnValue: _i2.Future<_i3.Order?>.value(),
          )
          as _i2.Future<_i3.Order?>);

  @override
  _i2.Future<List<_i3.Order>> getByUserId(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getByUserId, [userId]),
            returnValue: _i2.Future<List<_i3.Order>>.value(<_i3.Order>[]),
          )
          as _i2.Future<List<_i3.Order>>);

  @override
  _i2.Future<List<_i3.Order>> getByFisherId(String? fisherId) =>
      (super.noSuchMethod(
            Invocation.method(#getByFisherId, [fisherId]),
            returnValue: _i2.Future<List<_i3.Order>>.value(<_i3.Order>[]),
          )
          as _i2.Future<List<_i3.Order>>);

  @override
  _i2.Future<List<_i3.Order>> getByBuyerId(String? buyerId) =>
      (super.noSuchMethod(
            Invocation.method(#getByBuyerId, [buyerId]),
            returnValue: _i2.Future<List<_i3.Order>>.value(<_i3.Order>[]),
          )
          as _i2.Future<List<_i3.Order>>);

  @override
  _i2.Future<List<_i3.Order>> getByStatus(_i18.OrderStatus? status) =>
      (super.noSuchMethod(
            Invocation.method(#getByStatus, [status]),
            returnValue: _i2.Future<List<_i3.Order>>.value(<_i3.Order>[]),
          )
          as _i2.Future<List<_i3.Order>>);

  @override
  _i2.Future<List<_i3.Order>> getReviewableOrders(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getReviewableOrders, [userId]),
            returnValue: _i2.Future<List<_i3.Order>>.value(<_i3.Order>[]),
          )
          as _i2.Future<List<_i3.Order>>);

  @override
  _i2.Future<void> update(_i3.Order? order) =>
      (super.noSuchMethod(
            Invocation.method(#update, [order]),
            returnValue: _i2.Future<void>.value(),
            returnValueForMissingStub: _i2.Future<void>.value(),
          )
          as _i2.Future<void>);

  @override
  _i2.Future<void> delete(String? orderId) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [orderId]),
            returnValue: _i2.Future<void>.value(),
            returnValueForMissingStub: _i2.Future<void>.value(),
          )
          as _i2.Future<void>);

  @override
  _i2.Future<T> transaction<T>(_i2.Future<T> Function()? action) =>
      (super.noSuchMethod(
            Invocation.method(#transaction, [action]),
            returnValue:
                _i11.ifNotNull(
                  _i11.dummyValueOrNull<T>(
                    this,
                    Invocation.method(#transaction, [action]),
                  ),
                  (T v) => _i2.Future<T>.value(v),
                ) ??
                _FakeFuture_0<T>(
                  this,
                  Invocation.method(#transaction, [action]),
                ),
          )
          as _i2.Future<T>);
}

/// A class which mocks [IReviewRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIReviewRepository extends _i1.Mock implements _i19.IReviewRepository {
  MockIReviewRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Future<String> create(_i6.Review? review) =>
      (super.noSuchMethod(
            Invocation.method(#create, [review]),
            returnValue: _i2.Future<String>.value(
              _i11.dummyValue<String>(
                this,
                Invocation.method(#create, [review]),
              ),
            ),
          )
          as _i2.Future<String>);

  @override
  _i2.Future<_i6.Review?> getById(String? reviewId) =>
      (super.noSuchMethod(
            Invocation.method(#getById, [reviewId]),
            returnValue: _i2.Future<_i6.Review?>.value(),
          )
          as _i2.Future<_i6.Review?>);

  @override
  _i2.Future<List<_i6.Review>> getReviewsForUser(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getReviewsForUser, [userId]),
            returnValue: _i2.Future<List<_i6.Review>>.value(<_i6.Review>[]),
          )
          as _i2.Future<List<_i6.Review>>);

  @override
  _i2.Future<List<_i6.Review>> getReviewsByUser(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getReviewsByUser, [userId]),
            returnValue: _i2.Future<List<_i6.Review>>.value(<_i6.Review>[]),
          )
          as _i2.Future<List<_i6.Review>>);

  @override
  _i2.Future<List<_i6.Review>> getReviewsForOrder(String? orderId) =>
      (super.noSuchMethod(
            Invocation.method(#getReviewsForOrder, [orderId]),
            returnValue: _i2.Future<List<_i6.Review>>.value(<_i6.Review>[]),
          )
          as _i2.Future<List<_i6.Review>>);

  @override
  _i2.Future<bool> hasReview({
    required String? orderId,
    required String? reviewerId,
    required String? reviewedUserId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#hasReview, [], {
              #orderId: orderId,
              #reviewerId: reviewerId,
              #reviewedUserId: reviewedUserId,
            }),
            returnValue: _i2.Future<bool>.value(false),
          )
          as _i2.Future<bool>);

  @override
  _i2.Future<void> delete(String? reviewId) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [reviewId]),
            returnValue: _i2.Future<void>.value(),
            returnValueForMissingStub: _i2.Future<void>.value(),
          )
          as _i2.Future<void>);

  @override
  _i2.Future<T> transaction<T>(_i2.Future<T> Function()? action) =>
      (super.noSuchMethod(
            Invocation.method(#transaction, [action]),
            returnValue:
                _i11.ifNotNull(
                  _i11.dummyValueOrNull<T>(
                    this,
                    Invocation.method(#transaction, [action]),
                  ),
                  (T v) => _i2.Future<T>.value(v),
                ) ??
                _FakeFuture_0<T>(
                  this,
                  Invocation.method(#transaction, [action]),
                ),
          )
          as _i2.Future<T>);
}

/// A class which mocks [ISessionRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockISessionRepository extends _i1.Mock
    implements _i20.ISessionRepository {
  MockISessionRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Future<_i7.User?> getCurrentUser() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentUser, []),
            returnValue: _i2.Future<_i7.User?>.value(),
          )
          as _i2.Future<_i7.User?>);

  @override
  _i2.Future<_i14.UserRole?> getCurrentRole() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentRole, []),
            returnValue: _i2.Future<_i14.UserRole?>.value(),
          )
          as _i2.Future<_i14.UserRole?>);

  @override
  _i2.Future<void> saveCurrentUser(_i7.User? user) =>
      (super.noSuchMethod(
            Invocation.method(#saveCurrentUser, [user]),
            returnValue: _i2.Future<void>.value(),
            returnValueForMissingStub: _i2.Future<void>.value(),
          )
          as _i2.Future<void>);

  @override
  _i2.Future<void> saveCurrentRole(_i14.UserRole? role) =>
      (super.noSuchMethod(
            Invocation.method(#saveCurrentRole, [role]),
            returnValue: _i2.Future<void>.value(),
            returnValueForMissingStub: _i2.Future<void>.value(),
          )
          as _i2.Future<void>);

  @override
  _i2.Future<void> clearSession() =>
      (super.noSuchMethod(
            Invocation.method(#clearSession, []),
            returnValue: _i2.Future<void>.value(),
            returnValueForMissingStub: _i2.Future<void>.value(),
          )
          as _i2.Future<void>);

  @override
  _i2.Future<bool> isLoggedIn() =>
      (super.noSuchMethod(
            Invocation.method(#isLoggedIn, []),
            returnValue: _i2.Future<bool>.value(false),
          )
          as _i2.Future<bool>);
}

/// A class which mocks [IUserRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIUserRepository extends _i1.Mock implements _i21.IUserRepository {
  MockIUserRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Future<_i7.User?> getById(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getById, [userId]),
            returnValue: _i2.Future<_i7.User?>.value(),
          )
          as _i2.Future<_i7.User?>);

  @override
  _i2.Future<List<_i7.User>> getByIds(List<String>? userIds) =>
      (super.noSuchMethod(
            Invocation.method(#getByIds, [userIds]),
            returnValue: _i2.Future<List<_i7.User>>.value(<_i7.User>[]),
          )
          as _i2.Future<List<_i7.User>>);

  @override
  _i2.Future<void> updateRole(String? userId, _i14.UserRole? role) =>
      (super.noSuchMethod(
            Invocation.method(#updateRole, [userId, role]),
            returnValue: _i2.Future<void>.value(),
            returnValueForMissingStub: _i2.Future<void>.value(),
          )
          as _i2.Future<void>);

  @override
  _i2.Future<void> updateRating({
    required String? userId,
    required _i22.Rating? rating,
    required int? reviewCount,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateRating, [], {
              #userId: userId,
              #rating: rating,
              #reviewCount: reviewCount,
            }),
            returnValue: _i2.Future<void>.value(),
            returnValueForMissingStub: _i2.Future<void>.value(),
          )
          as _i2.Future<void>);

  @override
  _i2.Future<void> update(_i7.User? user) =>
      (super.noSuchMethod(
            Invocation.method(#update, [user]),
            returnValue: _i2.Future<void>.value(),
            returnValueForMissingStub: _i2.Future<void>.value(),
          )
          as _i2.Future<void>);

  @override
  _i2.Future<bool> exists(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#exists, [userId]),
            returnValue: _i2.Future<bool>.value(false),
          )
          as _i2.Future<bool>);

  @override
  _i2.Future<void> create(_i7.User? user) =>
      (super.noSuchMethod(
            Invocation.method(#create, [user]),
            returnValue: _i2.Future<void>.value(),
            returnValueForMissingStub: _i2.Future<void>.value(),
          )
          as _i2.Future<void>);

  @override
  _i2.Future<_i7.User?> getFirstFisher() =>
      (super.noSuchMethod(
            Invocation.method(#getFirstFisher, []),
            returnValue: _i2.Future<_i7.User?>.value(),
          )
          as _i2.Future<_i7.User?>);

  @override
  _i2.Future<_i7.User?> getFirstBuyer() =>
      (super.noSuchMethod(
            Invocation.method(#getFirstBuyer, []),
            returnValue: _i2.Future<_i7.User?>.value(),
          )
          as _i2.Future<_i7.User?>);
}

/// A class which mocks [IProductRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIProductRepository extends _i1.Mock
    implements _i23.IProductRepository {
  MockIProductRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Future<_i24.Either<_i25.Failure, List<_i26.Product>>> getFisherProducts({
    int? page = 1,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getFisherProducts, [], {#page: page}),
            returnValue:
                _i2.Future<_i24.Either<_i25.Failure, List<_i26.Product>>>.value(
                  _i11.dummyValue<
                    _i24.Either<_i25.Failure, List<_i26.Product>>
                  >(
                    this,
                    Invocation.method(#getFisherProducts, [], {#page: page}),
                  ),
                ),
          )
          as _i2.Future<_i24.Either<_i25.Failure, List<_i26.Product>>>);

  @override
  _i2.Future<_i24.Either<_i25.Failure, _i26.Product?>> getProductById(
    String? id,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getProductById, [id]),
            returnValue:
                _i2.Future<_i24.Either<_i25.Failure, _i26.Product?>>.value(
                  _i11.dummyValue<_i24.Either<_i25.Failure, _i26.Product?>>(
                    this,
                    Invocation.method(#getProductById, [id]),
                  ),
                ),
          )
          as _i2.Future<_i24.Either<_i25.Failure, _i26.Product?>>);

  @override
  _i2.Future<_i24.Either<_i25.Failure, List<_i5.Offer>>> getProductOffers(
    String? productId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getProductOffers, [productId]),
            returnValue:
                _i2.Future<_i24.Either<_i25.Failure, List<_i5.Offer>>>.value(
                  _i11.dummyValue<_i24.Either<_i25.Failure, List<_i5.Offer>>>(
                    this,
                    Invocation.method(#getProductOffers, [productId]),
                  ),
                ),
          )
          as _i2.Future<_i24.Either<_i25.Failure, List<_i5.Offer>>>);

  @override
  _i2.Future<_i24.Either<_i25.Failure, bool>> deleteProduct(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteProduct, [id]),
            returnValue: _i2.Future<_i24.Either<_i25.Failure, bool>>.value(
              _i11.dummyValue<_i24.Either<_i25.Failure, bool>>(
                this,
                Invocation.method(#deleteProduct, [id]),
              ),
            ),
          )
          as _i2.Future<_i24.Either<_i25.Failure, bool>>);

  @override
  _i2.Future<_i24.Either<_i25.Failure, _i26.Product>> updateProduct(
    String? id, {
    required double? pricePerKg,
    required double? finalPrice,
    required double? availableWeight,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #updateProduct,
              [id],
              {
                #pricePerKg: pricePerKg,
                #finalPrice: finalPrice,
                #availableWeight: availableWeight,
              },
            ),
            returnValue:
                _i2.Future<_i24.Either<_i25.Failure, _i26.Product>>.value(
                  _i11.dummyValue<_i24.Either<_i25.Failure, _i26.Product>>(
                    this,
                    Invocation.method(
                      #updateProduct,
                      [id],
                      {
                        #pricePerKg: pricePerKg,
                        #finalPrice: finalPrice,
                        #availableWeight: availableWeight,
                      },
                    ),
                  ),
                ),
          )
          as _i2.Future<_i24.Either<_i25.Failure, _i26.Product>>);

  @override
  _i2.Future<_i24.Either<_i25.Failure, List<_i26.Product>>>
  getAvailableProducts() =>
      (super.noSuchMethod(
            Invocation.method(#getAvailableProducts, []),
            returnValue:
                _i2.Future<_i24.Either<_i25.Failure, List<_i26.Product>>>.value(
                  _i11.dummyValue<
                    _i24.Either<_i25.Failure, List<_i26.Product>>
                  >(this, Invocation.method(#getAvailableProducts, [])),
                ),
          )
          as _i2.Future<_i24.Either<_i25.Failure, List<_i26.Product>>>);
}

/// A class which mocks [MessageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockMessageService extends _i1.Mock implements _i27.MessageService {
  MockMessageService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Future<_i4.Message> sendMessage({
    required String? senderId,
    required String? receiverId,
    required String? content,
    bool? isSystemMessage = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#sendMessage, [], {
              #senderId: senderId,
              #receiverId: receiverId,
              #content: content,
              #isSystemMessage: isSystemMessage,
            }),
            returnValue: _i2.Future<_i4.Message>.value(
              _FakeMessage_2(
                this,
                Invocation.method(#sendMessage, [], {
                  #senderId: senderId,
                  #receiverId: receiverId,
                  #content: content,
                  #isSystemMessage: isSystemMessage,
                }),
              ),
            ),
          )
          as _i2.Future<_i4.Message>);

  @override
  _i2.Future<void> sendOfferAcceptedMessage(_i3.Order? order) =>
      (super.noSuchMethod(
            Invocation.method(#sendOfferAcceptedMessage, [order]),
            returnValue: _i2.Future<void>.value(),
            returnValueForMissingStub: _i2.Future<void>.value(),
          )
          as _i2.Future<void>);

  @override
  _i2.Future<List<_i4.Message>> getConversationMessages({
    required String? conversationId,
    required String? currentUserId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getConversationMessages, [], {
              #conversationId: conversationId,
              #currentUserId: currentUserId,
            }),
            returnValue: _i2.Future<List<_i4.Message>>.value(<_i4.Message>[]),
          )
          as _i2.Future<List<_i4.Message>>);

  @override
  _i2.Future<int> getTotalUnreadCount(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getTotalUnreadCount, [userId]),
            returnValue: _i2.Future<int>.value(0),
          )
          as _i2.Future<int>);

  @override
  _i2.Future<void> markConversationAsRead(
    String? conversationId,
    String? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#markConversationAsRead, [
              conversationId,
              userId,
            ]),
            returnValue: _i2.Future<void>.value(),
            returnValueForMissingStub: _i2.Future<void>.value(),
          )
          as _i2.Future<void>);
}

/// A class which mocks [NegotiationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockNegotiationService extends _i1.Mock
    implements _i28.NegotiationService {
  MockNegotiationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Future<_i5.Offer> createOffer({
    required String? productId,
    required String? buyerId,
    required String? fisherId,
    required _i16.OfferTerms? terms,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createOffer, [], {
              #productId: productId,
              #buyerId: buyerId,
              #fisherId: fisherId,
              #terms: terms,
            }),
            returnValue: _i2.Future<_i5.Offer>.value(
              _FakeOffer_3(
                this,
                Invocation.method(#createOffer, [], {
                  #productId: productId,
                  #buyerId: buyerId,
                  #fisherId: fisherId,
                  #terms: terms,
                }),
              ),
            ),
          )
          as _i2.Future<_i5.Offer>);

  @override
  _i2.Future<_i3.Order> acceptOffer({
    required String? offerId,
    required String? userId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#acceptOffer, [], {
              #offerId: offerId,
              #userId: userId,
            }),
            returnValue: _i2.Future<_i3.Order>.value(
              _FakeOrder_1(
                this,
                Invocation.method(#acceptOffer, [], {
                  #offerId: offerId,
                  #userId: userId,
                }),
              ),
            ),
          )
          as _i2.Future<_i3.Order>);

  @override
  _i2.Future<_i5.Offer> rejectOffer({
    required String? offerId,
    required String? userId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#rejectOffer, [], {
              #offerId: offerId,
              #userId: userId,
            }),
            returnValue: _i2.Future<_i5.Offer>.value(
              _FakeOffer_3(
                this,
                Invocation.method(#rejectOffer, [], {
                  #offerId: offerId,
                  #userId: userId,
                }),
              ),
            ),
          )
          as _i2.Future<_i5.Offer>);

  @override
  _i2.Future<_i5.Offer> counterOffer({
    required String? offerId,
    required String? userId,
    required _i16.OfferTerms? newTerms,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#counterOffer, [], {
              #offerId: offerId,
              #userId: userId,
              #newTerms: newTerms,
            }),
            returnValue: _i2.Future<_i5.Offer>.value(
              _FakeOffer_3(
                this,
                Invocation.method(#counterOffer, [], {
                  #offerId: offerId,
                  #userId: userId,
                  #newTerms: newTerms,
                }),
              ),
            ),
          )
          as _i2.Future<_i5.Offer>);

  @override
  _i2.Future<void> relistOrder({
    required String? orderId,
    required String? reason,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#relistOrder, [], {
              #orderId: orderId,
              #reason: reason,
            }),
            returnValue: _i2.Future<void>.value(),
            returnValueForMissingStub: _i2.Future<void>.value(),
          )
          as _i2.Future<void>);

  @override
  _i2.Future<List<_i5.Offer>> getPendingOffersForUser(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getPendingOffersForUser, [userId]),
            returnValue: _i2.Future<List<_i5.Offer>>.value(<_i5.Offer>[]),
          )
          as _i2.Future<List<_i5.Offer>>);
}

/// A class which mocks [RatingService].
///
/// See the documentation for Mockito's code generation for more information.
class MockRatingService extends _i1.Mock implements _i29.RatingService {
  MockRatingService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Future<_i6.Review> submitReview({
    required String? orderId,
    required String? reviewerId,
    required String? reviewedUserId,
    required _i22.Rating? rating,
    String? comment,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#submitReview, [], {
              #orderId: orderId,
              #reviewerId: reviewerId,
              #reviewedUserId: reviewedUserId,
              #rating: rating,
              #comment: comment,
            }),
            returnValue: _i2.Future<_i6.Review>.value(
              _FakeReview_4(
                this,
                Invocation.method(#submitReview, [], {
                  #orderId: orderId,
                  #reviewerId: reviewerId,
                  #reviewedUserId: reviewedUserId,
                  #rating: rating,
                  #comment: comment,
                }),
              ),
            ),
          )
          as _i2.Future<_i6.Review>);

  @override
  _i2.Future<List<_i6.Review>> getReviewsForUser(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getReviewsForUser, [userId]),
            returnValue: _i2.Future<List<_i6.Review>>.value(<_i6.Review>[]),
          )
          as _i2.Future<List<_i6.Review>>);

  @override
  _i2.Future<List<_i3.Order>> getReviewableOrders(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getReviewableOrders, [userId]),
            returnValue: _i2.Future<List<_i3.Order>>.value(<_i3.Order>[]),
          )
          as _i2.Future<List<_i3.Order>>);
}

/// A class which mocks [SessionService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSessionService extends _i1.Mock implements _i30.SessionService {
  MockSessionService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Future<_i7.User?> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i2.Future<_i7.User?>.value(),
          )
          as _i2.Future<_i7.User?>);

  @override
  _i2.Future<_i7.User?> getCurrentUser() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentUser, []),
            returnValue: _i2.Future<_i7.User?>.value(),
          )
          as _i2.Future<_i7.User?>);

  @override
  _i2.Future<_i14.UserRole?> getCurrentRole() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentRole, []),
            returnValue: _i2.Future<_i14.UserRole?>.value(),
          )
          as _i2.Future<_i14.UserRole?>);

  @override
  _i2.Future<void> switchRole(_i14.UserRole? newRole) =>
      (super.noSuchMethod(
            Invocation.method(#switchRole, [newRole]),
            returnValue: _i2.Future<void>.value(),
            returnValueForMissingStub: _i2.Future<void>.value(),
          )
          as _i2.Future<void>);

  @override
  _i2.Future<_i7.User> loginWithApi(String? email, String? password) =>
      (super.noSuchMethod(
            Invocation.method(#loginWithApi, [email, password]),
            returnValue: _i2.Future<_i7.User>.value(
              _FakeUser_5(
                this,
                Invocation.method(#loginWithApi, [email, password]),
              ),
            ),
          )
          as _i2.Future<_i7.User>);

  @override
  _i2.Future<void> login(_i7.User? user) =>
      (super.noSuchMethod(
            Invocation.method(#login, [user]),
            returnValue: _i2.Future<void>.value(),
            returnValueForMissingStub: _i2.Future<void>.value(),
          )
          as _i2.Future<void>);

  @override
  _i2.Future<void> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i2.Future<void>.value(),
            returnValueForMissingStub: _i2.Future<void>.value(),
          )
          as _i2.Future<void>);

  @override
  _i2.Future<bool> isLoggedIn() =>
      (super.noSuchMethod(
            Invocation.method(#isLoggedIn, []),
            returnValue: _i2.Future<bool>.value(false),
          )
          as _i2.Future<bool>);
}

/// A class which mocks [ICatchDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockICatchDataSource extends _i1.Mock implements _i31.ICatchDataSource {
  MockICatchDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Future<String> create(_i32.CatchModel? catchItem) =>
      (super.noSuchMethod(
            Invocation.method(#create, [catchItem]),
            returnValue: _i2.Future<String>.value(
              _i11.dummyValue<String>(
                this,
                Invocation.method(#create, [catchItem]),
              ),
            ),
          )
          as _i2.Future<String>);

  @override
  _i2.Future<_i32.CatchModel?> getById(String? catchId) =>
      (super.noSuchMethod(
            Invocation.method(#getById, [catchId]),
            returnValue: _i2.Future<_i32.CatchModel?>.value(),
          )
          as _i2.Future<_i32.CatchModel?>);

  @override
  _i2.Future<List<_i32.CatchModel>> getByFisherId(String? fisherId) =>
      (super.noSuchMethod(
            Invocation.method(#getByFisherId, [fisherId]),
            returnValue: _i2.Future<List<_i32.CatchModel>>.value(
              <_i32.CatchModel>[],
            ),
          )
          as _i2.Future<List<_i32.CatchModel>>);

  @override
  _i2.Future<List<_i32.CatchModel>> getByStatus(_i12.CatchStatus? status) =>
      (super.noSuchMethod(
            Invocation.method(#getByStatus, [status]),
            returnValue: _i2.Future<List<_i32.CatchModel>>.value(
              <_i32.CatchModel>[],
            ),
          )
          as _i2.Future<List<_i32.CatchModel>>);

  @override
  _i2.Future<List<_i32.CatchModel>> getAll() =>
      (super.noSuchMethod(
            Invocation.method(#getAll, []),
            returnValue: _i2.Future<List<_i32.CatchModel>>.value(
              <_i32.CatchModel>[],
            ),
          )
          as _i2.Future<List<_i32.CatchModel>>);

  @override
  _i2.Future<void> update(_i32.CatchModel? catchItem) =>
      (super.noSuchMethod(
            Invocation.method(#update, [catchItem]),
            returnValue: _i2.Future<void>.value(),
            returnValueForMissingStub: _i2.Future<void>.value(),
          )
          as _i2.Future<void>);

  @override
  _i2.Future<void> delete(String? catchId) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [catchId]),
            returnValue: _i2.Future<void>.value(),
            returnValueForMissingStub: _i2.Future<void>.value(),
          )
          as _i2.Future<void>);

  @override
  _i2.Future<void> updateBatch(List<_i32.CatchModel>? catches) =>
      (super.noSuchMethod(
            Invocation.method(#updateBatch, [catches]),
            returnValue: _i2.Future<void>.value(),
            returnValueForMissingStub: _i2.Future<void>.value(),
          )
          as _i2.Future<void>);

  @override
  _i2.Future<void> deleteBatch(List<String>? catchIds) =>
      (super.noSuchMethod(
            Invocation.method(#deleteBatch, [catchIds]),
            returnValue: _i2.Future<void>.value(),
            returnValueForMissingStub: _i2.Future<void>.value(),
          )
          as _i2.Future<void>);
}

/// A class which mocks [IOfferDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockIOfferDataSource extends _i1.Mock implements _i33.IOfferDataSource {
  MockIOfferDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Future<String> create(_i8.OfferModel? offer) =>
      (super.noSuchMethod(
            Invocation.method(#create, [offer]),
            returnValue: _i2.Future<String>.value(
              _i11.dummyValue<String>(
                this,
                Invocation.method(#create, [offer]),
              ),
            ),
          )
          as _i2.Future<String>);

  @override
  _i2.Future<String> counterOffer(
    String? offerId,
    _i34.CounterOfferRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#counterOffer, [offerId, request]),
            returnValue: _i2.Future<String>.value(
              _i11.dummyValue<String>(
                this,
                Invocation.method(#counterOffer, [offerId, request]),
              ),
            ),
          )
          as _i2.Future<String>);

  @override
  _i2.Future<_i8.OfferModel> respond(
    String? offerId,
    _i34.OfferResponseRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#respond, [offerId, request]),
            returnValue: _i2.Future<_i8.OfferModel>.value(
              _FakeOfferModel_6(
                this,
                Invocation.method(#respond, [offerId, request]),
              ),
            ),
          )
          as _i2.Future<_i8.OfferModel>);

  @override
  _i2.Future<List<_i8.OfferModel>> getAllOffers() =>
      (super.noSuchMethod(
            Invocation.method(#getAllOffers, []),
            returnValue: _i2.Future<List<_i8.OfferModel>>.value(
              <_i8.OfferModel>[],
            ),
          )
          as _i2.Future<List<_i8.OfferModel>>);

  @override
  _i2.Future<_i8.OfferModel?> getById(String? offerId) =>
      (super.noSuchMethod(
            Invocation.method(#getById, [offerId]),
            returnValue: _i2.Future<_i8.OfferModel?>.value(),
          )
          as _i2.Future<_i8.OfferModel?>);

  @override
  _i2.Future<List<_i8.OfferModel>> getByProductId(
    String? productId, {
    _i14.UserRole? role,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getByProductId, [productId], {#role: role}),
            returnValue: _i2.Future<List<_i8.OfferModel>>.value(
              <_i8.OfferModel>[],
            ),
          )
          as _i2.Future<List<_i8.OfferModel>>);

  @override
  _i2.Future<List<_i8.OfferModel>> getByBuyerId(String? buyerId) =>
      (super.noSuchMethod(
            Invocation.method(#getByBuyerId, [buyerId]),
            returnValue: _i2.Future<List<_i8.OfferModel>>.value(
              <_i8.OfferModel>[],
            ),
          )
          as _i2.Future<List<_i8.OfferModel>>);

  @override
  _i2.Future<List<_i8.OfferModel>> getByFisherId(String? fisherId) =>
      (super.noSuchMethod(
            Invocation.method(#getByFisherId, [fisherId]),
            returnValue: _i2.Future<List<_i8.OfferModel>>.value(
              <_i8.OfferModel>[],
            ),
          )
          as _i2.Future<List<_i8.OfferModel>>);

  @override
  _i2.Future<List<_i8.OfferModel>> getByCatchIds(List<String>? catchIds) =>
      (super.noSuchMethod(
            Invocation.method(#getByCatchIds, [catchIds]),
            returnValue: _i2.Future<List<_i8.OfferModel>>.value(
              <_i8.OfferModel>[],
            ),
          )
          as _i2.Future<List<_i8.OfferModel>>);

  @override
  _i2.Future<List<_i8.OfferModel>> getByStatus(_i15.OfferStatus? status) =>
      (super.noSuchMethod(
            Invocation.method(#getByStatus, [status]),
            returnValue: _i2.Future<List<_i8.OfferModel>>.value(
              <_i8.OfferModel>[],
            ),
          )
          as _i2.Future<List<_i8.OfferModel>>);

  @override
  _i2.Future<void> update(_i8.OfferModel? offer) =>
      (super.noSuchMethod(
            Invocation.method(#update, [offer]),
            returnValue: _i2.Future<void>.value(),
            returnValueForMissingStub: _i2.Future<void>.value(),
          )
          as _i2.Future<void>);

  @override
  _i2.Future<void> delete(String? offerId) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [offerId]),
            returnValue: _i2.Future<void>.value(),
            returnValueForMissingStub: _i2.Future<void>.value(),
          )
          as _i2.Future<void>);

  @override
  _i2.Future<T> transaction<T>(_i2.Future<T> Function()? action) =>
      (super.noSuchMethod(
            Invocation.method(#transaction, [action]),
            returnValue:
                _i11.ifNotNull(
                  _i11.dummyValueOrNull<T>(
                    this,
                    Invocation.method(#transaction, [action]),
                  ),
                  (T v) => _i2.Future<T>.value(v),
                ) ??
                _FakeFuture_0<T>(
                  this,
                  Invocation.method(#transaction, [action]),
                ),
          )
          as _i2.Future<T>);

  @override
  void updateLocalCache(_i8.OfferModel? offer) => super.noSuchMethod(
    Invocation.method(#updateLocalCache, [offer]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [IOrderDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockIOrderDataSource extends _i1.Mock implements _i35.IOrderDataSource {
  MockIOrderDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Future<String> create(_i36.OrderModel? order) =>
      (super.noSuchMethod(
            Invocation.method(#create, [order]),
            returnValue: _i2.Future<String>.value(
              _i11.dummyValue<String>(
                this,
                Invocation.method(#create, [order]),
              ),
            ),
          )
          as _i2.Future<String>);

  @override
  _i2.Future<List<_i36.OrderModel>> getAllOrders() =>
      (super.noSuchMethod(
            Invocation.method(#getAllOrders, []),
            returnValue: _i2.Future<List<_i36.OrderModel>>.value(
              <_i36.OrderModel>[],
            ),
          )
          as _i2.Future<List<_i36.OrderModel>>);

  @override
  _i2.Future<_i36.OrderModel?> getById(String? orderId) =>
      (super.noSuchMethod(
            Invocation.method(#getById, [orderId]),
            returnValue: _i2.Future<_i36.OrderModel?>.value(),
          )
          as _i2.Future<_i36.OrderModel?>);

  @override
  _i2.Future<_i36.OrderModel?> getByOfferId(String? offerId) =>
      (super.noSuchMethod(
            Invocation.method(#getByOfferId, [offerId]),
            returnValue: _i2.Future<_i36.OrderModel?>.value(),
          )
          as _i2.Future<_i36.OrderModel?>);

  @override
  _i2.Future<List<_i36.OrderModel>> getByUserId(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getByUserId, [userId]),
            returnValue: _i2.Future<List<_i36.OrderModel>>.value(
              <_i36.OrderModel>[],
            ),
          )
          as _i2.Future<List<_i36.OrderModel>>);

  @override
  _i2.Future<List<_i36.OrderModel>> getByFisherId(String? fisherId) =>
      (super.noSuchMethod(
            Invocation.method(#getByFisherId, [fisherId]),
            returnValue: _i2.Future<List<_i36.OrderModel>>.value(
              <_i36.OrderModel>[],
            ),
          )
          as _i2.Future<List<_i36.OrderModel>>);

  @override
  _i2.Future<List<_i36.OrderModel>> getByBuyerId(String? buyerId) =>
      (super.noSuchMethod(
            Invocation.method(#getByBuyerId, [buyerId]),
            returnValue: _i2.Future<List<_i36.OrderModel>>.value(
              <_i36.OrderModel>[],
            ),
          )
          as _i2.Future<List<_i36.OrderModel>>);

  @override
  _i2.Future<List<_i36.OrderModel>> getByStatus(_i18.OrderStatus? status) =>
      (super.noSuchMethod(
            Invocation.method(#getByStatus, [status]),
            returnValue: _i2.Future<List<_i36.OrderModel>>.value(
              <_i36.OrderModel>[],
            ),
          )
          as _i2.Future<List<_i36.OrderModel>>);

  @override
  _i2.Future<void> update(_i36.OrderModel? order) =>
      (super.noSuchMethod(
            Invocation.method(#update, [order]),
            returnValue: _i2.Future<void>.value(),
            returnValueForMissingStub: _i2.Future<void>.value(),
          )
          as _i2.Future<void>);

  @override
  _i2.Future<void> delete(String? orderId) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [orderId]),
            returnValue: _i2.Future<void>.value(),
            returnValueForMissingStub: _i2.Future<void>.value(),
          )
          as _i2.Future<void>);

  @override
  _i2.Future<T> transaction<T>(_i2.Future<T> Function()? action) =>
      (super.noSuchMethod(
            Invocation.method(#transaction, [action]),
            returnValue:
                _i11.ifNotNull(
                  _i11.dummyValueOrNull<T>(
                    this,
                    Invocation.method(#transaction, [action]),
                  ),
                  (T v) => _i2.Future<T>.value(v),
                ) ??
                _FakeFuture_0<T>(
                  this,
                  Invocation.method(#transaction, [action]),
                ),
          )
          as _i2.Future<T>);
}

/// A class which mocks [IReviewDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockIReviewDataSource extends _i1.Mock implements _i37.IReviewDataSource {
  MockIReviewDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Future<String> create(_i38.ReviewModel? review) =>
      (super.noSuchMethod(
            Invocation.method(#create, [review]),
            returnValue: _i2.Future<String>.value(
              _i11.dummyValue<String>(
                this,
                Invocation.method(#create, [review]),
              ),
            ),
          )
          as _i2.Future<String>);

  @override
  _i2.Future<_i38.ReviewModel?> getById(String? reviewId) =>
      (super.noSuchMethod(
            Invocation.method(#getById, [reviewId]),
            returnValue: _i2.Future<_i38.ReviewModel?>.value(),
          )
          as _i2.Future<_i38.ReviewModel?>);

  @override
  _i2.Future<List<_i38.ReviewModel>> getReviewsForUser(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getReviewsForUser, [userId]),
            returnValue: _i2.Future<List<_i38.ReviewModel>>.value(
              <_i38.ReviewModel>[],
            ),
          )
          as _i2.Future<List<_i38.ReviewModel>>);

  @override
  _i2.Future<List<_i38.ReviewModel>> getReviewsByUser(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getReviewsByUser, [userId]),
            returnValue: _i2.Future<List<_i38.ReviewModel>>.value(
              <_i38.ReviewModel>[],
            ),
          )
          as _i2.Future<List<_i38.ReviewModel>>);

  @override
  _i2.Future<List<_i38.ReviewModel>> getReviewsForOrder(String? orderId) =>
      (super.noSuchMethod(
            Invocation.method(#getReviewsForOrder, [orderId]),
            returnValue: _i2.Future<List<_i38.ReviewModel>>.value(
              <_i38.ReviewModel>[],
            ),
          )
          as _i2.Future<List<_i38.ReviewModel>>);

  @override
  _i2.Future<bool> hasReview({
    required String? orderId,
    required String? reviewerId,
    required String? reviewedUserId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#hasReview, [], {
              #orderId: orderId,
              #reviewerId: reviewerId,
              #reviewedUserId: reviewedUserId,
            }),
            returnValue: _i2.Future<bool>.value(false),
          )
          as _i2.Future<bool>);

  @override
  _i2.Future<void> delete(String? reviewId) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [reviewId]),
            returnValue: _i2.Future<void>.value(),
            returnValueForMissingStub: _i2.Future<void>.value(),
          )
          as _i2.Future<void>);

  @override
  _i2.Future<T> transaction<T>(_i2.Future<T> Function()? action) =>
      (super.noSuchMethod(
            Invocation.method(#transaction, [action]),
            returnValue:
                _i11.ifNotNull(
                  _i11.dummyValueOrNull<T>(
                    this,
                    Invocation.method(#transaction, [action]),
                  ),
                  (T v) => _i2.Future<T>.value(v),
                ) ??
                _FakeFuture_0<T>(
                  this,
                  Invocation.method(#transaction, [action]),
                ),
          )
          as _i2.Future<T>);
}

/// A class which mocks [ISessionDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockISessionDataSource extends _i1.Mock
    implements _i39.ISessionDataSource {
  MockISessionDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Future<_i40.UserModel?> getCurrentUser() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentUser, []),
            returnValue: _i2.Future<_i40.UserModel?>.value(),
          )
          as _i2.Future<_i40.UserModel?>);

  @override
  _i2.Future<String?> getCurrentRole() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentRole, []),
            returnValue: _i2.Future<String?>.value(),
          )
          as _i2.Future<String?>);

  @override
  _i2.Future<void> saveCurrentUser(_i40.UserModel? user) =>
      (super.noSuchMethod(
            Invocation.method(#saveCurrentUser, [user]),
            returnValue: _i2.Future<void>.value(),
            returnValueForMissingStub: _i2.Future<void>.value(),
          )
          as _i2.Future<void>);

  @override
  _i2.Future<void> saveCurrentRole(String? role) =>
      (super.noSuchMethod(
            Invocation.method(#saveCurrentRole, [role]),
            returnValue: _i2.Future<void>.value(),
            returnValueForMissingStub: _i2.Future<void>.value(),
          )
          as _i2.Future<void>);

  @override
  _i2.Future<void> clearSession() =>
      (super.noSuchMethod(
            Invocation.method(#clearSession, []),
            returnValue: _i2.Future<void>.value(),
            returnValueForMissingStub: _i2.Future<void>.value(),
          )
          as _i2.Future<void>);

  @override
  _i2.Future<bool> isLoggedIn() =>
      (super.noSuchMethod(
            Invocation.method(#isLoggedIn, []),
            returnValue: _i2.Future<bool>.value(false),
          )
          as _i2.Future<bool>);
}

/// A class which mocks [IUserDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockIUserDataSource extends _i1.Mock implements _i41.IUserDataSource {
  MockIUserDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Future<_i40.UserModel?> getById(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getById, [userId]),
            returnValue: _i2.Future<_i40.UserModel?>.value(),
          )
          as _i2.Future<_i40.UserModel?>);

  @override
  _i2.Future<List<_i40.UserModel>> getByIds(List<String>? userIds) =>
      (super.noSuchMethod(
            Invocation.method(#getByIds, [userIds]),
            returnValue: _i2.Future<List<_i40.UserModel>>.value(
              <_i40.UserModel>[],
            ),
          )
          as _i2.Future<List<_i40.UserModel>>);

  @override
  _i2.Future<void> create(_i40.UserModel? user) =>
      (super.noSuchMethod(
            Invocation.method(#create, [user]),
            returnValue: _i2.Future<void>.value(),
            returnValueForMissingStub: _i2.Future<void>.value(),
          )
          as _i2.Future<void>);

  @override
  _i2.Future<void> update(_i40.UserModel? user) =>
      (super.noSuchMethod(
            Invocation.method(#update, [user]),
            returnValue: _i2.Future<void>.value(),
            returnValueForMissingStub: _i2.Future<void>.value(),
          )
          as _i2.Future<void>);

  @override
  _i2.Future<void> updateRating({
    required String? userId,
    required double? rating,
    required int? reviewCount,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateRating, [], {
              #userId: userId,
              #rating: rating,
              #reviewCount: reviewCount,
            }),
            returnValue: _i2.Future<void>.value(),
            returnValueForMissingStub: _i2.Future<void>.value(),
          )
          as _i2.Future<void>);

  @override
  _i2.Future<bool> exists(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#exists, [userId]),
            returnValue: _i2.Future<bool>.value(false),
          )
          as _i2.Future<bool>);

  @override
  _i2.Future<_i40.UserModel?> getFirstFisher() =>
      (super.noSuchMethod(
            Invocation.method(#getFirstFisher, []),
            returnValue: _i2.Future<_i40.UserModel?>.value(),
          )
          as _i2.Future<_i40.UserModel?>);

  @override
  _i2.Future<_i40.UserModel?> getFirstBuyer() =>
      (super.noSuchMethod(
            Invocation.method(#getFirstBuyer, []),
            returnValue: _i2.Future<_i40.UserModel?>.value(),
          )
          as _i2.Future<_i40.UserModel?>);
}
