import 'package:dio/dio.dart';
import '../storage/token_storage.dart';
import 'api_config.dart';

/// Interceptor to add JWT token to requests and handle token refresh
class ApiInterceptor extends Interceptor {
  final TokenStorage _tokenStorage;
  final Dio _dio;

  ApiInterceptor(this._tokenStorage, this._dio);

  @override
  Future<void> onRequest(
    RequestOptions options,
    RequestInterceptorHandler handler,
  ) async {
    // Skip token for auth endpoints
    if (options.path.contains('/auth/login')) {
      return handler.next(options);
    }

    // DISABLED: Proactive token refresh
    // API returns 501 (Not Implemented) for refresh endpoint
    // Token will be cleared on 401 errors instead
    /*
    if (await _tokenStorage.isTokenExpired()) {
      print('DEBUG: Token expired, attempting proactive refresh');
      final refreshed = await _tryRefreshToken();
      print('DEBUG: Proactive refresh result: $refreshed');
      if (!refreshed) {
        await _tokenStorage.clearTokens();
        return handler.reject(
          DioException(
            requestOptions: options,
            response: Response(
              requestOptions: options,
              statusCode: 401,
              statusMessage: 'Session expired',
            ),
            type: DioExceptionType.badResponse,
            message: 'Session expired, please login again',
          ),
          true,
        );
      }
    }
    */

    // Add JWT token to headers
    final token = await _tokenStorage.getAccessToken();
    if (token != null) {
      print(
        'DEBUG: Adding token to header: Bearer ${token.substring(0, 10)}...',
      );
      options.headers['Authorization'] = 'Bearer $token';
    } else {
      print('DEBUG: No token found in storage');
    }

    return handler.next(options);
  }

  @override
  Future<void> onError(
    DioException err,
    ErrorInterceptorHandler handler,
  ) async {
    // Handle 401 Unauthorized - token expired or invalid
    if (err.response?.statusCode == 401) {
      // If this 401 was generated by our proactive check, don't try to refresh again
      if (err.response?.statusMessage == 'Session expired') {
        return handler.next(err);
      }

      // Try to refresh token
      final refreshed = await _tryRefreshToken();

      if (refreshed) {
        // Retry the original request
        try {
          final options = err.requestOptions;
          final token = await _tokenStorage.getAccessToken();
          options.headers['Authorization'] = 'Bearer $token';

          final response = await _dio.fetch(options);
          return handler.resolve(response);
        } catch (e) {
          return handler.next(err);
        }
      } else {
        // Refresh failed, clear tokens and let error propagate
        await _tokenStorage.clearTokens();
        return handler.next(err);
      }
    }

    return handler.next(err);
  }

  /// Attempt to refresh the access token
  /// API expects current token in Authorization header, returns new token
  Future<bool> _tryRefreshToken() async {
    try {
      final currentToken = await _tokenStorage.getAccessToken();
      if (currentToken == null) {
        print('DEBUG: No current token available for refresh');
        return false;
      }

      print('DEBUG: Attempting to refresh token...');

      // Create a new Dio instance to avoid interceptor loop
      final dio = Dio();
      final url = '${ApiConfig.coreBaseUrl}${ApiConfig.tokenRefresh}';

      final response = await dio.post(
        url,
        options: Options(
          headers: {'Authorization': 'Bearer $currentToken'},
          validateStatus: (status) => status != null && status < 500,
        ),
      );

      print('DEBUG: Refresh response status: ${response.statusCode}');

      if (response.statusCode == 200) {
        final data = response.data;
        final newToken = data['token'];
        final newExpiry = data['tokenExpireAt'];

        print('DEBUG: Refresh successful, got new token');

        if (newToken != null) {
          await _tokenStorage.saveAccessToken(newToken);

          // Parse and save new expiry if provided
          if (newExpiry != null) {
            try {
              final expiryDate = DateTime.parse(newExpiry);
              await _tokenStorage.saveTokenExpiry(expiryDate);
              print('DEBUG: New token expires at: $expiryDate');
            } catch (e) {
              print('DEBUG: Could not parse expiry date: $e');
            }
          }

          return true;
        }
      }

      print('DEBUG: Refresh failed with status ${response.statusCode}');
      return false;
    } catch (e) {
      print('DEBUG: Refresh error: $e');
      return false;
    }
  }
}
