import 'package:dio/dio.dart';
import '../storage/token_storage.dart';
import 'api_config.dart';

/// Interceptor to add JWT token to requests and handle token refresh
class ApiInterceptor extends Interceptor {
  final TokenStorage _tokenStorage;
  final Dio _dio;

  ApiInterceptor(this._tokenStorage, this._dio);

  @override
  Future<void> onRequest(
    RequestOptions options,
    RequestInterceptorHandler handler,
  ) async {
    // Skip token for auth endpoints
    if (options.path.contains('/auth/login')) {
      return handler.next(options);
    }

    // Check for proactive refresh
    if (await _tokenStorage.isTokenExpired()) {
      print('DEBUG: Token expired, attempting proactive refresh');
      final refreshed = await _tryRefreshToken();
      print('DEBUG: Proactive refresh result: $refreshed');
      if (!refreshed) {
        // If refresh failed, we can't do much but clear tokens
        await _tokenStorage.clearTokens();

        // Reject the request immediately with 401 to trigger logout
        return handler.reject(
          DioException(
            requestOptions: options,
            response: Response(
              requestOptions: options,
              statusCode: 401,
              statusMessage: 'Session expired',
            ),
            type: DioExceptionType.badResponse,
            message: 'Session expired, please login again',
          ),
          true, // Call following error interceptor, though 401 might be handled by UI or SessionService
        );
      }
    }

    // Add JWT token to headers
    final token = await _tokenStorage.getAccessToken();
    if (token != null) {
      print(
        'DEBUG: Adding token to header: Bearer ${token.substring(0, 10)}...',
      );
      options.headers['Authorization'] = 'Bearer $token';
    } else {
      print('DEBUG: No token found in storage');
    }

    return handler.next(options);
  }

  @override
  Future<void> onError(
    DioException err,
    ErrorInterceptorHandler handler,
  ) async {
    // Handle 401 Unauthorized - token expired or invalid
    if (err.response?.statusCode == 401) {
      // If this 401 was generated by our proactive check, don't try to refresh again
      if (err.response?.statusMessage == 'Session expired') {
        return handler.next(err);
      }

      // Try to refresh token
      final refreshed = await _tryRefreshToken();

      if (refreshed) {
        // Retry the original request
        try {
          final options = err.requestOptions;
          final token = await _tokenStorage.getAccessToken();
          options.headers['Authorization'] = 'Bearer $token';

          final response = await _dio.fetch(options);
          return handler.resolve(response);
        } catch (e) {
          return handler.next(err);
        }
      } else {
        // Refresh failed, clear tokens and let error propagate
        await _tokenStorage.clearTokens();
        return handler.next(err);
      }
    }

    return handler.next(err);
  }

  /// Attempt to refresh the access token
  Future<bool> _tryRefreshToken() async {
    try {
      final refreshToken = await _tokenStorage.getRefreshToken();
      if (refreshToken == null) return false;

      // Create a new Dio instance to avoid interceptor loop
      final dio = Dio();
      // Use Core base URL + token refresh endpoint
      final url = '${ApiConfig.coreBaseUrl}${ApiConfig.tokenRefresh}';

      final response = await dio.post(
        url,
        data: {'refresh_token': refreshToken},
        options: Options(
          validateStatus: (status) => status != null && status < 500,
        ),
      );

      if (response.statusCode == 200) {
        final data = response.data;
        // Assuming response matches AuthorizeResponse or contains token/refreshToken
        final newToken = data['token'];
        final newRefreshToken = data['refresh_token'];

        if (newToken != null) {
          await _tokenStorage.saveAccessToken(newToken);
        }
        if (newRefreshToken != null) {
          await _tokenStorage.saveRefreshToken(newRefreshToken);
        }
        return true;
      }

      return false;
    } catch (e) {
      return false;
    }
  }
}
